export const SET_REQUEST = 'SET_REQUEST'
export const SET_REQUEST_POINT = 'SET_REQUEST_POINT'

export const SET_REQUEST_ASYNC = 'SET_REQUEST_ASYNC'
export const SET_REQUEST_POINT_ASYNC = 'SET_REQUEST_POINT_ASYNC'
